/*
 * Generated by orval v5.4.14 🍺
 * Do not edit manually.
 * FordConnect Prod Collection V3.1.2
 * OpenAPI spec version: 1.0.0
 */

export type GetApiFordconnectVehiclesV1VehicleIdImagesThumbnailParams = { make?: string; model?: string; year?: number };
