/*
 * Generated by orval v5.4.14 🍺
 * Do not edit manually.
 * FordConnect Prod Collection V3.1.2
 * OpenAPI spec version: 1.0.0
 */

export type Post914d88b135234bf69be41b96b4f6f919Oauth2V20TokenParams = { p?: string };
